project_id = "bccvpirrqwhqsinlmpth"

[functions.tts]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.check-stripe-price]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.sync-plano-stripe]
verify_jwt = false

[functions.wa-duck-notify]
verify_jwt = false

[functions.waduk-webhook]
verify_jwt = false

[functions.wa-duck-webhook]
verify_jwt = false
