/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv.index'
import { Route as TvSlugRouteImport } from './routes/tv.$slug'
import { Route as TestLayoutsRouteImport } from './routes/test.layouts'
import { Route as TestHorizontalRouteImport } from './routes/test.horizontal'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as HooksHealthcheckRouteImport } from './routes/hooks/healthcheck'
import { Route as HooksCleanupTtsCacheRouteImport } from './routes/hooks/cleanup-tts-cache'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as AppAppVozRouteImport } from './routes/_app.app.voz'
import { Route as AppAppTvRouteImport } from './routes/_app.app.tv'
import { Route as AppAppRelatoriosRouteImport } from './routes/_app.app.relatorios'
import { Route as AppAppRecepcaoRouteImport } from './routes/_app.app.recepcao'
import { Route as AppAppPacientesRouteImport } from './routes/_app.app.pacientes'
import { Route as AppAppNotificacoesRouteImport } from './routes/_app.app.notificacoes'
import { Route as AppAppFilasRouteImport } from './routes/_app.app.filas'
import { Route as AppAppContaRouteImport } from './routes/_app.app.conta'
import { Route as AppAppAuditoriaRouteImport } from './routes/_app.app.auditoria'
import { Route as AppAppAtendimentoRouteImport } from './routes/_app.app.atendimento'
import { Route as AdminAdminPlanosRouteImport } from './routes/_admin.admin.planos'
import { Route as AdminAdminMetricasRouteImport } from './routes/_admin.admin.metricas'
import { Route as AdminAdminLogsRouteImport } from './routes/_admin.admin.logs'
import { Route as AdminAdminAuditoriaRouteImport } from './routes/_admin.admin.auditoria'
import { Route as AdminAdminAlertasRouteImport } from './routes/_admin.admin.alertas'
import { Route as AdminAdminUnidadesUnidadeIdRouteImport } from './routes/_admin.admin.unidades.$unidadeId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSlugRoute = TvSlugRouteImport.update({
  id: '/tv/$slug',
  path: '/tv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestLayoutsRoute = TestLayoutsRouteImport.update({
  id: '/test/layouts',
  path: '/test/layouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHorizontalRoute = TestHorizontalRouteImport.update({
  id: '/test/horizontal',
  path: '/test/horizontal',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksHealthcheckRoute = HooksHealthcheckRouteImport.update({
  id: '/hooks/healthcheck',
  path: '/hooks/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksCleanupTtsCacheRoute = HooksCleanupTtsCacheRouteImport.update({
  id: '/hooks/cleanup-tts-cache',
  path: '/hooks/cleanup-tts-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppVozRoute = AppAppVozRouteImport.update({
  id: '/voz',
  path: '/voz',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppTvRoute = AppAppTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppRelatoriosRoute = AppAppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppRecepcaoRoute = AppAppRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppPacientesRoute = AppAppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppNotificacoesRoute = AppAppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppFilasRoute = AppAppFilasRouteImport.update({
  id: '/filas',
  path: '/filas',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppContaRoute = AppAppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAuditoriaRoute = AppAppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAtendimentoRoute = AppAppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppAppRoute,
} as any)
const AdminAdminPlanosRoute = AdminAdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMetricasRoute = AdminAdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLogsRoute = AdminAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditoriaRoute = AdminAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAlertasRoute = AdminAdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUnidadesUnidadeIdRoute =
  AdminAdminUnidadesUnidadeIdRouteImport.update({
    id: '/unidades/$unidadeId',
    path: '/unidades/$unidadeId',
    getParentRoute: () => AdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casos': typeof CasosRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/app': typeof AppAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/hooks/cleanup-tts-cache': typeof HooksCleanupTtsCacheRoute
  '/hooks/healthcheck': typeof HooksHealthcheckRoute
  '/s/$token': typeof STokenRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/layouts': typeof TestLayoutsRoute
  '/tv/$slug': typeof TvSlugRoute
  '/tv/': typeof TvIndexRoute
  '/admin/alertas': typeof AdminAdminAlertasRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/metricas': typeof AdminAdminMetricasRoute
  '/admin/planos': typeof AdminAdminPlanosRoute
  '/app/atendimento': typeof AppAppAtendimentoRoute
  '/app/auditoria': typeof AppAppAuditoriaRoute
  '/app/conta': typeof AppAppContaRoute
  '/app/filas': typeof AppAppFilasRoute
  '/app/notificacoes': typeof AppAppNotificacoesRoute
  '/app/pacientes': typeof AppAppPacientesRoute
  '/app/recepcao': typeof AppAppRecepcaoRoute
  '/app/relatorios': typeof AppAppRelatoriosRoute
  '/app/tv': typeof AppAppTvRoute
  '/app/voz': typeof AppAppVozRoute
  '/app/': typeof AppAppIndexRoute
  '/admin/unidades/$unidadeId': typeof AdminAdminUnidadesUnidadeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casos': typeof CasosRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/hooks/cleanup-tts-cache': typeof HooksCleanupTtsCacheRoute
  '/hooks/healthcheck': typeof HooksHealthcheckRoute
  '/s/$token': typeof STokenRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/layouts': typeof TestLayoutsRoute
  '/tv/$slug': typeof TvSlugRoute
  '/tv': typeof TvIndexRoute
  '/admin/alertas': typeof AdminAdminAlertasRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/metricas': typeof AdminAdminMetricasRoute
  '/admin/planos': typeof AdminAdminPlanosRoute
  '/app/atendimento': typeof AppAppAtendimentoRoute
  '/app/auditoria': typeof AppAppAuditoriaRoute
  '/app/conta': typeof AppAppContaRoute
  '/app/filas': typeof AppAppFilasRoute
  '/app/notificacoes': typeof AppAppNotificacoesRoute
  '/app/pacientes': typeof AppAppPacientesRoute
  '/app/recepcao': typeof AppAppRecepcaoRoute
  '/app/relatorios': typeof AppAppRelatoriosRoute
  '/app/tv': typeof AppAppTvRoute
  '/app/voz': typeof AppAppVozRoute
  '/app': typeof AppAppIndexRoute
  '/admin/unidades/$unidadeId': typeof AdminAdminUnidadesUnidadeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/casos': typeof CasosRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/setup': typeof SetupRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/app': typeof AppAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/hooks/cleanup-tts-cache': typeof HooksCleanupTtsCacheRoute
  '/hooks/healthcheck': typeof HooksHealthcheckRoute
  '/s/$token': typeof STokenRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/layouts': typeof TestLayoutsRoute
  '/tv/$slug': typeof TvSlugRoute
  '/tv/': typeof TvIndexRoute
  '/_admin/admin/alertas': typeof AdminAdminAlertasRoute
  '/_admin/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/_admin/admin/logs': typeof AdminAdminLogsRoute
  '/_admin/admin/metricas': typeof AdminAdminMetricasRoute
  '/_admin/admin/planos': typeof AdminAdminPlanosRoute
  '/_app/app/atendimento': typeof AppAppAtendimentoRoute
  '/_app/app/auditoria': typeof AppAppAuditoriaRoute
  '/_app/app/conta': typeof AppAppContaRoute
  '/_app/app/filas': typeof AppAppFilasRoute
  '/_app/app/notificacoes': typeof AppAppNotificacoesRoute
  '/_app/app/pacientes': typeof AppAppPacientesRoute
  '/_app/app/recepcao': typeof AppAppRecepcaoRoute
  '/_app/app/relatorios': typeof AppAppRelatoriosRoute
  '/_app/app/tv': typeof AppAppTvRoute
  '/_app/app/voz': typeof AppAppVozRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_admin/admin/unidades/$unidadeId': typeof AdminAdminUnidadesUnidadeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casos'
    | '/login'
    | '/precos'
    | '/setup'
    | '/admin'
    | '/app'
    | '/checkout/return'
    | '/hooks/cleanup-tts-cache'
    | '/hooks/healthcheck'
    | '/s/$token'
    | '/test/horizontal'
    | '/test/layouts'
    | '/tv/$slug'
    | '/tv/'
    | '/admin/alertas'
    | '/admin/auditoria'
    | '/admin/logs'
    | '/admin/metricas'
    | '/admin/planos'
    | '/app/atendimento'
    | '/app/auditoria'
    | '/app/conta'
    | '/app/filas'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/recepcao'
    | '/app/relatorios'
    | '/app/tv'
    | '/app/voz'
    | '/app/'
    | '/admin/unidades/$unidadeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casos'
    | '/login'
    | '/precos'
    | '/setup'
    | '/admin'
    | '/checkout/return'
    | '/hooks/cleanup-tts-cache'
    | '/hooks/healthcheck'
    | '/s/$token'
    | '/test/horizontal'
    | '/test/layouts'
    | '/tv/$slug'
    | '/tv'
    | '/admin/alertas'
    | '/admin/auditoria'
    | '/admin/logs'
    | '/admin/metricas'
    | '/admin/planos'
    | '/app/atendimento'
    | '/app/auditoria'
    | '/app/conta'
    | '/app/filas'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/recepcao'
    | '/app/relatorios'
    | '/app/tv'
    | '/app/voz'
    | '/app'
    | '/admin/unidades/$unidadeId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/casos'
    | '/login'
    | '/precos'
    | '/setup'
    | '/_admin/admin'
    | '/_app/app'
    | '/checkout/return'
    | '/hooks/cleanup-tts-cache'
    | '/hooks/healthcheck'
    | '/s/$token'
    | '/test/horizontal'
    | '/test/layouts'
    | '/tv/$slug'
    | '/tv/'
    | '/_admin/admin/alertas'
    | '/_admin/admin/auditoria'
    | '/_admin/admin/logs'
    | '/_admin/admin/metricas'
    | '/_admin/admin/planos'
    | '/_app/app/atendimento'
    | '/_app/app/auditoria'
    | '/_app/app/conta'
    | '/_app/app/filas'
    | '/_app/app/notificacoes'
    | '/_app/app/pacientes'
    | '/_app/app/recepcao'
    | '/_app/app/relatorios'
    | '/_app/app/tv'
    | '/_app/app/voz'
    | '/_app/app/'
    | '/_admin/admin/unidades/$unidadeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CasosRoute: typeof CasosRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  SetupRoute: typeof SetupRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  HooksCleanupTtsCacheRoute: typeof HooksCleanupTtsCacheRoute
  HooksHealthcheckRoute: typeof HooksHealthcheckRoute
  STokenRoute: typeof STokenRoute
  TestHorizontalRoute: typeof TestHorizontalRoute
  TestLayoutsRoute: typeof TestLayoutsRoute
  TvSlugRoute: typeof TvSlugRoute
  TvIndexRoute: typeof TvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$slug': {
      id: '/tv/$slug'
      path: '/tv/$slug'
      fullPath: '/tv/$slug'
      preLoaderRoute: typeof TvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/layouts': {
      id: '/test/layouts'
      path: '/test/layouts'
      fullPath: '/test/layouts'
      preLoaderRoute: typeof TestLayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/horizontal': {
      id: '/test/horizontal'
      path: '/test/horizontal'
      fullPath: '/test/horizontal'
      preLoaderRoute: typeof TestHorizontalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/healthcheck': {
      id: '/hooks/healthcheck'
      path: '/hooks/healthcheck'
      fullPath: '/hooks/healthcheck'
      preLoaderRoute: typeof HooksHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/cleanup-tts-cache': {
      id: '/hooks/cleanup-tts-cache'
      path: '/hooks/cleanup-tts-cache'
      fullPath: '/hooks/cleanup-tts-cache'
      preLoaderRoute: typeof HooksCleanupTtsCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/voz': {
      id: '/_app/app/voz'
      path: '/voz'
      fullPath: '/app/voz'
      preLoaderRoute: typeof AppAppVozRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/tv': {
      id: '/_app/app/tv'
      path: '/tv'
      fullPath: '/app/tv'
      preLoaderRoute: typeof AppAppTvRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/relatorios': {
      id: '/_app/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppAppRelatoriosRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/recepcao': {
      id: '/_app/app/recepcao'
      path: '/recepcao'
      fullPath: '/app/recepcao'
      preLoaderRoute: typeof AppAppRecepcaoRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/pacientes': {
      id: '/_app/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppAppPacientesRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/notificacoes': {
      id: '/_app/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppAppNotificacoesRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/filas': {
      id: '/_app/app/filas'
      path: '/filas'
      fullPath: '/app/filas'
      preLoaderRoute: typeof AppAppFilasRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/conta': {
      id: '/_app/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppAppContaRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/auditoria': {
      id: '/_app/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAppAuditoriaRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/atendimento': {
      id: '/_app/app/atendimento'
      path: '/atendimento'
      fullPath: '/app/atendimento'
      preLoaderRoute: typeof AppAppAtendimentoRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_admin/admin/planos': {
      id: '/_admin/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminAdminPlanosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/metricas': {
      id: '/_admin/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminAdminMetricasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/logs': {
      id: '/_admin/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminAdminLogsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/auditoria': {
      id: '/_admin/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAdminAuditoriaRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/alertas': {
      id: '/_admin/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAdminAlertasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/unidades/$unidadeId': {
      id: '/_admin/admin/unidades/$unidadeId'
      path: '/unidades/$unidadeId'
      fullPath: '/admin/unidades/$unidadeId'
      preLoaderRoute: typeof AdminAdminUnidadesUnidadeIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAlertasRoute: typeof AdminAdminAlertasRoute
  AdminAdminAuditoriaRoute: typeof AdminAdminAuditoriaRoute
  AdminAdminLogsRoute: typeof AdminAdminLogsRoute
  AdminAdminMetricasRoute: typeof AdminAdminMetricasRoute
  AdminAdminPlanosRoute: typeof AdminAdminPlanosRoute
  AdminAdminUnidadesUnidadeIdRoute: typeof AdminAdminUnidadesUnidadeIdRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAlertasRoute: AdminAdminAlertasRoute,
  AdminAdminAuditoriaRoute: AdminAdminAuditoriaRoute,
  AdminAdminLogsRoute: AdminAdminLogsRoute,
  AdminAdminMetricasRoute: AdminAdminMetricasRoute,
  AdminAdminPlanosRoute: AdminAdminPlanosRoute,
  AdminAdminUnidadesUnidadeIdRoute: AdminAdminUnidadesUnidadeIdRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAppRouteChildren {
  AppAppAtendimentoRoute: typeof AppAppAtendimentoRoute
  AppAppAuditoriaRoute: typeof AppAppAuditoriaRoute
  AppAppContaRoute: typeof AppAppContaRoute
  AppAppFilasRoute: typeof AppAppFilasRoute
  AppAppNotificacoesRoute: typeof AppAppNotificacoesRoute
  AppAppPacientesRoute: typeof AppAppPacientesRoute
  AppAppRecepcaoRoute: typeof AppAppRecepcaoRoute
  AppAppRelatoriosRoute: typeof AppAppRelatoriosRoute
  AppAppTvRoute: typeof AppAppTvRoute
  AppAppVozRoute: typeof AppAppVozRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppAtendimentoRoute: AppAppAtendimentoRoute,
  AppAppAuditoriaRoute: AppAppAuditoriaRoute,
  AppAppContaRoute: AppAppContaRoute,
  AppAppFilasRoute: AppAppFilasRoute,
  AppAppNotificacoesRoute: AppAppNotificacoesRoute,
  AppAppPacientesRoute: AppAppPacientesRoute,
  AppAppRecepcaoRoute: AppAppRecepcaoRoute,
  AppAppRelatoriosRoute: AppAppRelatoriosRoute,
  AppAppTvRoute: AppAppTvRoute,
  AppAppVozRoute: AppAppVozRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CasosRoute: CasosRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  SetupRoute: SetupRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  HooksCleanupTtsCacheRoute: HooksCleanupTtsCacheRoute,
  HooksHealthcheckRoute: HooksHealthcheckRoute,
  STokenRoute: STokenRoute,
  TestHorizontalRoute: TestHorizontalRoute,
  TestLayoutsRoute: TestLayoutsRoute,
  TvSlugRoute: TvSlugRoute,
  TvIndexRoute: TvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
