/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv.index'
import { Route as TvSlugRouteImport } from './routes/tv.$slug'
import { Route as TestLayoutsRouteImport } from './routes/test.layouts'
import { Route as TestHorizontalRouteImport } from './routes/test.horizontal'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as RUnidadeIdRouteImport } from './routes/r.$unidadeId'
import { Route as OperacaoCrmRouteImport } from './routes/operacao.crm'
import { Route as HooksHealthcheckRouteImport } from './routes/hooks/healthcheck'
import { Route as HooksCleanupTtsCacheRouteImport } from './routes/hooks/cleanup-tts-cache'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AdminAdminRouteImport } from './routes/_admin.admin'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as AppAppVozRouteImport } from './routes/_app.app.voz'
import { Route as AppAppUsuariosRouteImport } from './routes/_app.app.usuarios'
import { Route as AppAppTvRouteImport } from './routes/_app.app.tv'
import { Route as AppAppTriagemRouteImport } from './routes/_app.app.triagem'
import { Route as AppAppSegurancaRouteImport } from './routes/_app.app.seguranca'
import { Route as AppAppRelatoriosRouteImport } from './routes/_app.app.relatorios'
import { Route as AppAppRecepcaoRouteImport } from './routes/_app.app.recepcao'
import { Route as AppAppPontosRouteImport } from './routes/_app.app.pontos'
import { Route as AppAppPacientesRouteImport } from './routes/_app.app.pacientes'
import { Route as AppAppNotificacoesRouteImport } from './routes/_app.app.notificacoes'
import { Route as AppAppGuicheRouteImport } from './routes/_app.app.guiche'
import { Route as AppAppFilasRouteImport } from './routes/_app.app.filas'
import { Route as AppAppContaRouteImport } from './routes/_app.app.conta'
import { Route as AppAppAuditoriaRouteImport } from './routes/_app.app.auditoria'
import { Route as AppAppAtendimentoRouteImport } from './routes/_app.app.atendimento'
import { Route as AdminAdminRevendasRouteImport } from './routes/_admin.admin.revendas'
import { Route as AdminAdminPlanosRouteImport } from './routes/_admin.admin.planos'
import { Route as AdminAdminMetricasRouteImport } from './routes/_admin.admin.metricas'
import { Route as AdminAdminLogsRouteImport } from './routes/_admin.admin.logs'
import { Route as AdminAdminCrmRouteImport } from './routes/_admin.admin.crm'
import { Route as AdminAdminClassificacaoRouteImport } from './routes/_admin.admin.classificacao'
import { Route as AdminAdminAutomacoesRouteImport } from './routes/_admin.admin.automacoes'
import { Route as AdminAdminAuditoriaRouteImport } from './routes/_admin.admin.auditoria'
import { Route as AdminAdminAlertasRouteImport } from './routes/_admin.admin.alertas'
import { Route as AdminAdminUnidadesUnidadeIdRouteImport } from './routes/_admin.admin.unidades.$unidadeId'
import { Route as AdminAdminUnidadesUnidadeIdMetricasRouteImport } from './routes/_admin.admin.unidades.$unidadeId.metricas'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSlugRoute = TvSlugRouteImport.update({
  id: '/tv/$slug',
  path: '/tv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestLayoutsRoute = TestLayoutsRouteImport.update({
  id: '/test/layouts',
  path: '/test/layouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TestHorizontalRoute = TestHorizontalRouteImport.update({
  id: '/test/horizontal',
  path: '/test/horizontal',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RUnidadeIdRoute = RUnidadeIdRouteImport.update({
  id: '/r/$unidadeId',
  path: '/r/$unidadeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoCrmRoute = OperacaoCrmRouteImport.update({
  id: '/operacao/crm',
  path: '/operacao/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksHealthcheckRoute = HooksHealthcheckRouteImport.update({
  id: '/hooks/healthcheck',
  path: '/hooks/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksCleanupTtsCacheRoute = HooksCleanupTtsCacheRouteImport.update({
  id: '/hooks/cleanup-tts-cache',
  path: '/hooks/cleanup-tts-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppVozRoute = AppAppVozRouteImport.update({
  id: '/voz',
  path: '/voz',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppUsuariosRoute = AppAppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppTvRoute = AppAppTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppTriagemRoute = AppAppTriagemRouteImport.update({
  id: '/triagem',
  path: '/triagem',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSegurancaRoute = AppAppSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppRelatoriosRoute = AppAppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppRecepcaoRoute = AppAppRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppPontosRoute = AppAppPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppPacientesRoute = AppAppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppNotificacoesRoute = AppAppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppGuicheRoute = AppAppGuicheRouteImport.update({
  id: '/guiche',
  path: '/guiche',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppFilasRoute = AppAppFilasRouteImport.update({
  id: '/filas',
  path: '/filas',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppContaRoute = AppAppContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAuditoriaRoute = AppAppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAtendimentoRoute = AppAppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppAppRoute,
} as any)
const AdminAdminRevendasRoute = AdminAdminRevendasRouteImport.update({
  id: '/revendas',
  path: '/revendas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPlanosRoute = AdminAdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMetricasRoute = AdminAdminMetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLogsRoute = AdminAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCrmRoute = AdminAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClassificacaoRoute = AdminAdminClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAutomacoesRoute = AdminAdminAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditoriaRoute = AdminAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAlertasRoute = AdminAdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUnidadesUnidadeIdRoute =
  AdminAdminUnidadesUnidadeIdRouteImport.update({
    id: '/unidades/$unidadeId',
    path: '/unidades/$unidadeId',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminUnidadesUnidadeIdMetricasRoute =
  AdminAdminUnidadesUnidadeIdMetricasRouteImport.update({
    id: '/metricas',
    path: '/metricas',
    getParentRoute: () => AdminAdminUnidadesUnidadeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/casos': typeof CasosRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/app': typeof AppAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/hooks/cleanup-tts-cache': typeof HooksCleanupTtsCacheRoute
  '/hooks/healthcheck': typeof HooksHealthcheckRoute
  '/operacao/crm': typeof OperacaoCrmRoute
  '/r/$unidadeId': typeof RUnidadeIdRoute
  '/s/$token': typeof STokenRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/layouts': typeof TestLayoutsRoute
  '/tv/$slug': typeof TvSlugRoute
  '/tv/': typeof TvIndexRoute
  '/admin/alertas': typeof AdminAdminAlertasRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/automacoes': typeof AdminAdminAutomacoesRoute
  '/admin/classificacao': typeof AdminAdminClassificacaoRoute
  '/admin/crm': typeof AdminAdminCrmRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/metricas': typeof AdminAdminMetricasRoute
  '/admin/planos': typeof AdminAdminPlanosRoute
  '/admin/revendas': typeof AdminAdminRevendasRoute
  '/app/atendimento': typeof AppAppAtendimentoRoute
  '/app/auditoria': typeof AppAppAuditoriaRoute
  '/app/conta': typeof AppAppContaRoute
  '/app/filas': typeof AppAppFilasRoute
  '/app/guiche': typeof AppAppGuicheRoute
  '/app/notificacoes': typeof AppAppNotificacoesRoute
  '/app/pacientes': typeof AppAppPacientesRoute
  '/app/pontos': typeof AppAppPontosRoute
  '/app/recepcao': typeof AppAppRecepcaoRoute
  '/app/relatorios': typeof AppAppRelatoriosRoute
  '/app/seguranca': typeof AppAppSegurancaRoute
  '/app/triagem': typeof AppAppTriagemRoute
  '/app/tv': typeof AppAppTvRoute
  '/app/usuarios': typeof AppAppUsuariosRoute
  '/app/voz': typeof AppAppVozRoute
  '/app/': typeof AppAppIndexRoute
  '/admin/unidades/$unidadeId': typeof AdminAdminUnidadesUnidadeIdRouteWithChildren
  '/admin/unidades/$unidadeId/metricas': typeof AdminAdminUnidadesUnidadeIdMetricasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/casos': typeof CasosRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/hooks/cleanup-tts-cache': typeof HooksCleanupTtsCacheRoute
  '/hooks/healthcheck': typeof HooksHealthcheckRoute
  '/operacao/crm': typeof OperacaoCrmRoute
  '/r/$unidadeId': typeof RUnidadeIdRoute
  '/s/$token': typeof STokenRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/layouts': typeof TestLayoutsRoute
  '/tv/$slug': typeof TvSlugRoute
  '/tv': typeof TvIndexRoute
  '/admin/alertas': typeof AdminAdminAlertasRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/automacoes': typeof AdminAdminAutomacoesRoute
  '/admin/classificacao': typeof AdminAdminClassificacaoRoute
  '/admin/crm': typeof AdminAdminCrmRoute
  '/admin/logs': typeof AdminAdminLogsRoute
  '/admin/metricas': typeof AdminAdminMetricasRoute
  '/admin/planos': typeof AdminAdminPlanosRoute
  '/admin/revendas': typeof AdminAdminRevendasRoute
  '/app/atendimento': typeof AppAppAtendimentoRoute
  '/app/auditoria': typeof AppAppAuditoriaRoute
  '/app/conta': typeof AppAppContaRoute
  '/app/filas': typeof AppAppFilasRoute
  '/app/guiche': typeof AppAppGuicheRoute
  '/app/notificacoes': typeof AppAppNotificacoesRoute
  '/app/pacientes': typeof AppAppPacientesRoute
  '/app/pontos': typeof AppAppPontosRoute
  '/app/recepcao': typeof AppAppRecepcaoRoute
  '/app/relatorios': typeof AppAppRelatoriosRoute
  '/app/seguranca': typeof AppAppSegurancaRoute
  '/app/triagem': typeof AppAppTriagemRoute
  '/app/tv': typeof AppAppTvRoute
  '/app/usuarios': typeof AppAppUsuariosRoute
  '/app/voz': typeof AppAppVozRoute
  '/app': typeof AppAppIndexRoute
  '/admin/unidades/$unidadeId': typeof AdminAdminUnidadesUnidadeIdRouteWithChildren
  '/admin/unidades/$unidadeId/metricas': typeof AdminAdminUnidadesUnidadeIdMetricasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/casos': typeof CasosRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/app': typeof AppAppRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/hooks/cleanup-tts-cache': typeof HooksCleanupTtsCacheRoute
  '/hooks/healthcheck': typeof HooksHealthcheckRoute
  '/operacao/crm': typeof OperacaoCrmRoute
  '/r/$unidadeId': typeof RUnidadeIdRoute
  '/s/$token': typeof STokenRoute
  '/test/horizontal': typeof TestHorizontalRoute
  '/test/layouts': typeof TestLayoutsRoute
  '/tv/$slug': typeof TvSlugRoute
  '/tv/': typeof TvIndexRoute
  '/_admin/admin/alertas': typeof AdminAdminAlertasRoute
  '/_admin/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/_admin/admin/automacoes': typeof AdminAdminAutomacoesRoute
  '/_admin/admin/classificacao': typeof AdminAdminClassificacaoRoute
  '/_admin/admin/crm': typeof AdminAdminCrmRoute
  '/_admin/admin/logs': typeof AdminAdminLogsRoute
  '/_admin/admin/metricas': typeof AdminAdminMetricasRoute
  '/_admin/admin/planos': typeof AdminAdminPlanosRoute
  '/_admin/admin/revendas': typeof AdminAdminRevendasRoute
  '/_app/app/atendimento': typeof AppAppAtendimentoRoute
  '/_app/app/auditoria': typeof AppAppAuditoriaRoute
  '/_app/app/conta': typeof AppAppContaRoute
  '/_app/app/filas': typeof AppAppFilasRoute
  '/_app/app/guiche': typeof AppAppGuicheRoute
  '/_app/app/notificacoes': typeof AppAppNotificacoesRoute
  '/_app/app/pacientes': typeof AppAppPacientesRoute
  '/_app/app/pontos': typeof AppAppPontosRoute
  '/_app/app/recepcao': typeof AppAppRecepcaoRoute
  '/_app/app/relatorios': typeof AppAppRelatoriosRoute
  '/_app/app/seguranca': typeof AppAppSegurancaRoute
  '/_app/app/triagem': typeof AppAppTriagemRoute
  '/_app/app/tv': typeof AppAppTvRoute
  '/_app/app/usuarios': typeof AppAppUsuariosRoute
  '/_app/app/voz': typeof AppAppVozRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_admin/admin/unidades/$unidadeId': typeof AdminAdminUnidadesUnidadeIdRouteWithChildren
  '/_admin/admin/unidades/$unidadeId/metricas': typeof AdminAdminUnidadesUnidadeIdMetricasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/casos'
    | '/demo'
    | '/login'
    | '/manual'
    | '/precos'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/app'
    | '/checkout/return'
    | '/convite/$token'
    | '/hooks/cleanup-tts-cache'
    | '/hooks/healthcheck'
    | '/operacao/crm'
    | '/r/$unidadeId'
    | '/s/$token'
    | '/test/horizontal'
    | '/test/layouts'
    | '/tv/$slug'
    | '/tv/'
    | '/admin/alertas'
    | '/admin/auditoria'
    | '/admin/automacoes'
    | '/admin/classificacao'
    | '/admin/crm'
    | '/admin/logs'
    | '/admin/metricas'
    | '/admin/planos'
    | '/admin/revendas'
    | '/app/atendimento'
    | '/app/auditoria'
    | '/app/conta'
    | '/app/filas'
    | '/app/guiche'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/pontos'
    | '/app/recepcao'
    | '/app/relatorios'
    | '/app/seguranca'
    | '/app/triagem'
    | '/app/tv'
    | '/app/usuarios'
    | '/app/voz'
    | '/app/'
    | '/admin/unidades/$unidadeId'
    | '/admin/unidades/$unidadeId/metricas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/casos'
    | '/demo'
    | '/login'
    | '/manual'
    | '/precos'
    | '/reset-password'
    | '/setup'
    | '/admin'
    | '/checkout/return'
    | '/convite/$token'
    | '/hooks/cleanup-tts-cache'
    | '/hooks/healthcheck'
    | '/operacao/crm'
    | '/r/$unidadeId'
    | '/s/$token'
    | '/test/horizontal'
    | '/test/layouts'
    | '/tv/$slug'
    | '/tv'
    | '/admin/alertas'
    | '/admin/auditoria'
    | '/admin/automacoes'
    | '/admin/classificacao'
    | '/admin/crm'
    | '/admin/logs'
    | '/admin/metricas'
    | '/admin/planos'
    | '/admin/revendas'
    | '/app/atendimento'
    | '/app/auditoria'
    | '/app/conta'
    | '/app/filas'
    | '/app/guiche'
    | '/app/notificacoes'
    | '/app/pacientes'
    | '/app/pontos'
    | '/app/recepcao'
    | '/app/relatorios'
    | '/app/seguranca'
    | '/app/triagem'
    | '/app/tv'
    | '/app/usuarios'
    | '/app/voz'
    | '/app'
    | '/admin/unidades/$unidadeId'
    | '/admin/unidades/$unidadeId/metricas'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_app'
    | '/casos'
    | '/demo'
    | '/login'
    | '/manual'
    | '/precos'
    | '/reset-password'
    | '/setup'
    | '/_admin/admin'
    | '/_app/app'
    | '/checkout/return'
    | '/convite/$token'
    | '/hooks/cleanup-tts-cache'
    | '/hooks/healthcheck'
    | '/operacao/crm'
    | '/r/$unidadeId'
    | '/s/$token'
    | '/test/horizontal'
    | '/test/layouts'
    | '/tv/$slug'
    | '/tv/'
    | '/_admin/admin/alertas'
    | '/_admin/admin/auditoria'
    | '/_admin/admin/automacoes'
    | '/_admin/admin/classificacao'
    | '/_admin/admin/crm'
    | '/_admin/admin/logs'
    | '/_admin/admin/metricas'
    | '/_admin/admin/planos'
    | '/_admin/admin/revendas'
    | '/_app/app/atendimento'
    | '/_app/app/auditoria'
    | '/_app/app/conta'
    | '/_app/app/filas'
    | '/_app/app/guiche'
    | '/_app/app/notificacoes'
    | '/_app/app/pacientes'
    | '/_app/app/pontos'
    | '/_app/app/recepcao'
    | '/_app/app/relatorios'
    | '/_app/app/seguranca'
    | '/_app/app/triagem'
    | '/_app/app/tv'
    | '/_app/app/usuarios'
    | '/_app/app/voz'
    | '/_app/app/'
    | '/_admin/admin/unidades/$unidadeId'
    | '/_admin/admin/unidades/$unidadeId/metricas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CasosRoute: typeof CasosRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  PrecosRoute: typeof PrecosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  HooksCleanupTtsCacheRoute: typeof HooksCleanupTtsCacheRoute
  HooksHealthcheckRoute: typeof HooksHealthcheckRoute
  OperacaoCrmRoute: typeof OperacaoCrmRoute
  RUnidadeIdRoute: typeof RUnidadeIdRoute
  STokenRoute: typeof STokenRoute
  TestHorizontalRoute: typeof TestHorizontalRoute
  TestLayoutsRoute: typeof TestLayoutsRoute
  TvSlugRoute: typeof TvSlugRoute
  TvIndexRoute: typeof TvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$slug': {
      id: '/tv/$slug'
      path: '/tv/$slug'
      fullPath: '/tv/$slug'
      preLoaderRoute: typeof TvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/layouts': {
      id: '/test/layouts'
      path: '/test/layouts'
      fullPath: '/test/layouts'
      preLoaderRoute: typeof TestLayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/horizontal': {
      id: '/test/horizontal'
      path: '/test/horizontal'
      fullPath: '/test/horizontal'
      preLoaderRoute: typeof TestHorizontalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$unidadeId': {
      id: '/r/$unidadeId'
      path: '/r/$unidadeId'
      fullPath: '/r/$unidadeId'
      preLoaderRoute: typeof RUnidadeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao/crm': {
      id: '/operacao/crm'
      path: '/operacao/crm'
      fullPath: '/operacao/crm'
      preLoaderRoute: typeof OperacaoCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/healthcheck': {
      id: '/hooks/healthcheck'
      path: '/hooks/healthcheck'
      fullPath: '/hooks/healthcheck'
      preLoaderRoute: typeof HooksHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/cleanup-tts-cache': {
      id: '/hooks/cleanup-tts-cache'
      path: '/hooks/cleanup-tts-cache'
      fullPath: '/hooks/cleanup-tts-cache'
      preLoaderRoute: typeof HooksCleanupTtsCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/voz': {
      id: '/_app/app/voz'
      path: '/voz'
      fullPath: '/app/voz'
      preLoaderRoute: typeof AppAppVozRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/usuarios': {
      id: '/_app/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppAppUsuariosRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/tv': {
      id: '/_app/app/tv'
      path: '/tv'
      fullPath: '/app/tv'
      preLoaderRoute: typeof AppAppTvRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/triagem': {
      id: '/_app/app/triagem'
      path: '/triagem'
      fullPath: '/app/triagem'
      preLoaderRoute: typeof AppAppTriagemRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/seguranca': {
      id: '/_app/app/seguranca'
      path: '/seguranca'
      fullPath: '/app/seguranca'
      preLoaderRoute: typeof AppAppSegurancaRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/relatorios': {
      id: '/_app/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppAppRelatoriosRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/recepcao': {
      id: '/_app/app/recepcao'
      path: '/recepcao'
      fullPath: '/app/recepcao'
      preLoaderRoute: typeof AppAppRecepcaoRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/pontos': {
      id: '/_app/app/pontos'
      path: '/pontos'
      fullPath: '/app/pontos'
      preLoaderRoute: typeof AppAppPontosRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/pacientes': {
      id: '/_app/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppAppPacientesRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/notificacoes': {
      id: '/_app/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppAppNotificacoesRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/guiche': {
      id: '/_app/app/guiche'
      path: '/guiche'
      fullPath: '/app/guiche'
      preLoaderRoute: typeof AppAppGuicheRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/filas': {
      id: '/_app/app/filas'
      path: '/filas'
      fullPath: '/app/filas'
      preLoaderRoute: typeof AppAppFilasRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/conta': {
      id: '/_app/app/conta'
      path: '/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AppAppContaRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/auditoria': {
      id: '/_app/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAppAuditoriaRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/atendimento': {
      id: '/_app/app/atendimento'
      path: '/atendimento'
      fullPath: '/app/atendimento'
      preLoaderRoute: typeof AppAppAtendimentoRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_admin/admin/revendas': {
      id: '/_admin/admin/revendas'
      path: '/revendas'
      fullPath: '/admin/revendas'
      preLoaderRoute: typeof AdminAdminRevendasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/planos': {
      id: '/_admin/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminAdminPlanosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/metricas': {
      id: '/_admin/admin/metricas'
      path: '/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminAdminMetricasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/logs': {
      id: '/_admin/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminAdminLogsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/crm': {
      id: '/_admin/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminAdminCrmRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/classificacao': {
      id: '/_admin/admin/classificacao'
      path: '/classificacao'
      fullPath: '/admin/classificacao'
      preLoaderRoute: typeof AdminAdminClassificacaoRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/automacoes': {
      id: '/_admin/admin/automacoes'
      path: '/automacoes'
      fullPath: '/admin/automacoes'
      preLoaderRoute: typeof AdminAdminAutomacoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/auditoria': {
      id: '/_admin/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAdminAuditoriaRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/alertas': {
      id: '/_admin/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAdminAlertasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/unidades/$unidadeId': {
      id: '/_admin/admin/unidades/$unidadeId'
      path: '/unidades/$unidadeId'
      fullPath: '/admin/unidades/$unidadeId'
      preLoaderRoute: typeof AdminAdminUnidadesUnidadeIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/unidades/$unidadeId/metricas': {
      id: '/_admin/admin/unidades/$unidadeId/metricas'
      path: '/metricas'
      fullPath: '/admin/unidades/$unidadeId/metricas'
      preLoaderRoute: typeof AdminAdminUnidadesUnidadeIdMetricasRouteImport
      parentRoute: typeof AdminAdminUnidadesUnidadeIdRoute
    }
  }
}

interface AdminAdminUnidadesUnidadeIdRouteChildren {
  AdminAdminUnidadesUnidadeIdMetricasRoute: typeof AdminAdminUnidadesUnidadeIdMetricasRoute
}

const AdminAdminUnidadesUnidadeIdRouteChildren: AdminAdminUnidadesUnidadeIdRouteChildren =
  {
    AdminAdminUnidadesUnidadeIdMetricasRoute:
      AdminAdminUnidadesUnidadeIdMetricasRoute,
  }

const AdminAdminUnidadesUnidadeIdRouteWithChildren =
  AdminAdminUnidadesUnidadeIdRoute._addFileChildren(
    AdminAdminUnidadesUnidadeIdRouteChildren,
  )

interface AdminAdminRouteChildren {
  AdminAdminAlertasRoute: typeof AdminAdminAlertasRoute
  AdminAdminAuditoriaRoute: typeof AdminAdminAuditoriaRoute
  AdminAdminAutomacoesRoute: typeof AdminAdminAutomacoesRoute
  AdminAdminClassificacaoRoute: typeof AdminAdminClassificacaoRoute
  AdminAdminCrmRoute: typeof AdminAdminCrmRoute
  AdminAdminLogsRoute: typeof AdminAdminLogsRoute
  AdminAdminMetricasRoute: typeof AdminAdminMetricasRoute
  AdminAdminPlanosRoute: typeof AdminAdminPlanosRoute
  AdminAdminRevendasRoute: typeof AdminAdminRevendasRoute
  AdminAdminUnidadesUnidadeIdRoute: typeof AdminAdminUnidadesUnidadeIdRouteWithChildren
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAlertasRoute: AdminAdminAlertasRoute,
  AdminAdminAuditoriaRoute: AdminAdminAuditoriaRoute,
  AdminAdminAutomacoesRoute: AdminAdminAutomacoesRoute,
  AdminAdminClassificacaoRoute: AdminAdminClassificacaoRoute,
  AdminAdminCrmRoute: AdminAdminCrmRoute,
  AdminAdminLogsRoute: AdminAdminLogsRoute,
  AdminAdminMetricasRoute: AdminAdminMetricasRoute,
  AdminAdminPlanosRoute: AdminAdminPlanosRoute,
  AdminAdminRevendasRoute: AdminAdminRevendasRoute,
  AdminAdminUnidadesUnidadeIdRoute:
    AdminAdminUnidadesUnidadeIdRouteWithChildren,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAppRouteChildren {
  AppAppAtendimentoRoute: typeof AppAppAtendimentoRoute
  AppAppAuditoriaRoute: typeof AppAppAuditoriaRoute
  AppAppContaRoute: typeof AppAppContaRoute
  AppAppFilasRoute: typeof AppAppFilasRoute
  AppAppGuicheRoute: typeof AppAppGuicheRoute
  AppAppNotificacoesRoute: typeof AppAppNotificacoesRoute
  AppAppPacientesRoute: typeof AppAppPacientesRoute
  AppAppPontosRoute: typeof AppAppPontosRoute
  AppAppRecepcaoRoute: typeof AppAppRecepcaoRoute
  AppAppRelatoriosRoute: typeof AppAppRelatoriosRoute
  AppAppSegurancaRoute: typeof AppAppSegurancaRoute
  AppAppTriagemRoute: typeof AppAppTriagemRoute
  AppAppTvRoute: typeof AppAppTvRoute
  AppAppUsuariosRoute: typeof AppAppUsuariosRoute
  AppAppVozRoute: typeof AppAppVozRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppAtendimentoRoute: AppAppAtendimentoRoute,
  AppAppAuditoriaRoute: AppAppAuditoriaRoute,
  AppAppContaRoute: AppAppContaRoute,
  AppAppFilasRoute: AppAppFilasRoute,
  AppAppGuicheRoute: AppAppGuicheRoute,
  AppAppNotificacoesRoute: AppAppNotificacoesRoute,
  AppAppPacientesRoute: AppAppPacientesRoute,
  AppAppPontosRoute: AppAppPontosRoute,
  AppAppRecepcaoRoute: AppAppRecepcaoRoute,
  AppAppRelatoriosRoute: AppAppRelatoriosRoute,
  AppAppSegurancaRoute: AppAppSegurancaRoute,
  AppAppTriagemRoute: AppAppTriagemRoute,
  AppAppTvRoute: AppAppTvRoute,
  AppAppUsuariosRoute: AppAppUsuariosRoute,
  AppAppVozRoute: AppAppVozRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CasosRoute: CasosRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  PrecosRoute: PrecosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  HooksCleanupTtsCacheRoute: HooksCleanupTtsCacheRoute,
  HooksHealthcheckRoute: HooksHealthcheckRoute,
  OperacaoCrmRoute: OperacaoCrmRoute,
  RUnidadeIdRoute: RUnidadeIdRoute,
  STokenRoute: STokenRoute,
  TestHorizontalRoute: TestHorizontalRoute,
  TestLayoutsRoute: TestLayoutsRoute,
  TvSlugRoute: TvSlugRoute,
  TvIndexRoute: TvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
